apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: luccostajr/gitops
  # every time image changes the sha value bellow will be updated
  newTag: sha
