apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

  # every time image changes the sha value bellow will be updated
images:
- name: goserver
  newName: luccostajr/gitops
  newTag: d6e90e9d40f1cdd35d46584fe3ece26c22dfd3cf
